//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MICRouterEntities : DbContext
    {
        public MICRouterEntities()
            : base("name=MICRouterEntities")
        {
      EF_FIX.FixEfProviderServicesProblem();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<super_managers> super_managers { get; set; }
        public virtual DbSet<super_place_types> super_place_types { get; set; }
        public virtual DbSet<super_places> super_places { get; set; }
        public virtual DbSet<super_properties> super_properties { get; set; }
        public virtual DbSet<super_states> super_states { get; set; }
        public virtual DbSet<super_territory_types> super_territory_types { get; set; }
        public virtual DbSet<super_work_types> super_work_types { get; set; }
        public virtual DbSet<super_works> super_works { get; set; }
        public virtual DbSet<supervisors> supervisors { get; set; }
        public virtual DbSet<super_manager_v> super_manager_v { get; set; }
        public virtual DbSet<super_state_list_v> super_state_list_v { get; set; }
        public virtual DbSet<super_territories_show_v> super_territories_show_v { get; set; }
        public virtual DbSet<super_territories_v> super_territories_v { get; set; }
        public virtual DbSet<super_territory_list_v> super_territory_list_v { get; set; }
        public virtual DbSet<super_v> super_v { get; set; }
        public virtual DbSet<super_work_type_list_v> super_work_type_list_v { get; set; }
        public virtual DbSet<place_list> place_list { get; set; }
        public virtual DbSet<super_agree_types> super_agree_types { get; set; }
        public virtual DbSet<super_agreements> super_agreements { get; set; }
    
        [DbFunction("MICRouterEntities", "super_current_states")]
        public virtual IQueryable<super_current_states_Result> super_current_states()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<super_current_states_Result>("[MICRouterEntities].[super_current_states]()");
        }
    
        public virtual int super_manager_add(Nullable<int> supervisor_id, string name, string phone, string email, string desc)
        {
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("super_manager_add", supervisor_idParameter, nameParameter, phoneParameter, emailParameter, descParameter);
        }
    
        public virtual int super_manager_delete(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> super_manager_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var super_manager_idParameter = super_manager_id.HasValue ?
                new ObjectParameter("super_manager_id", super_manager_id) :
                new ObjectParameter("super_manager_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("super_manager_delete", manager_idParameter, workplace_type_idParameter, super_manager_idParameter);
        }
    
        public virtual int super_manager_update(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> super_manager_id, Nullable<int> supervisor_id, string name, string phone, string email, string desc)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var super_manager_idParameter = super_manager_id.HasValue ?
                new ObjectParameter("super_manager_id", super_manager_id) :
                new ObjectParameter("super_manager_id", typeof(int));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("super_manager_update", manager_idParameter, workplace_type_idParameter, super_manager_idParameter, supervisor_idParameter, nameParameter, phoneParameter, emailParameter, descParameter);
        }
    
        public virtual ObjectResult<super_territories_show_Result> super_territories_show(Nullable<int> terr_list_id, Nullable<byte> state_id, Nullable<byte> work_type_id, Nullable<byte> agree_type_id, Nullable<int> tablet_count)
        {
            var terr_list_idParameter = terr_list_id.HasValue ?
                new ObjectParameter("terr_list_id", terr_list_id) :
                new ObjectParameter("terr_list_id", typeof(int));
    
            var state_idParameter = state_id.HasValue ?
                new ObjectParameter("state_id", state_id) :
                new ObjectParameter("state_id", typeof(byte));
    
            var work_type_idParameter = work_type_id.HasValue ?
                new ObjectParameter("work_type_id", work_type_id) :
                new ObjectParameter("work_type_id", typeof(byte));
    
            var agree_type_idParameter = agree_type_id.HasValue ?
                new ObjectParameter("agree_type_id", agree_type_id) :
                new ObjectParameter("agree_type_id", typeof(byte));
    
            var tablet_countParameter = tablet_count.HasValue ?
                new ObjectParameter("tablet_count", tablet_count) :
                new ObjectParameter("tablet_count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<super_territories_show_Result>("super_territories_show", terr_list_idParameter, state_idParameter, work_type_idParameter, agree_type_idParameter, tablet_countParameter);
        }
    
        public virtual int supervisor_add(Nullable<int> manager_id, Nullable<byte> workplace_type_id, string name_fact, Nullable<byte> state_id, string name_law, string head_name, string head_comment, string head_phone_work, string head_phone_home, string head_phone_mobile, string fax, string http, string head_email, string field_name, string field_comment, string field_phone_work, string field_phone_home, string field_phone_mobile, string field_email, Nullable<short> inter_count, string address_fact, string address_law, Nullable<short> computer_count, Nullable<short> manager_count, string iNN, string kPP, Nullable<bool> vAT, string vAT_argument, string recvisits, string description, string fin_head, string fin_position, string work_on, string ind_licence, string ind_tax, string ind_inn, string ind_register, string desc_control, string login, string password, string folder, Nullable<int> dictaphone, Nullable<int> notebook, Nullable<int> computer, Nullable<int> pda)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var name_factParameter = name_fact != null ?
                new ObjectParameter("name_fact", name_fact) :
                new ObjectParameter("name_fact", typeof(string));
    
            var state_idParameter = state_id.HasValue ?
                new ObjectParameter("state_id", state_id) :
                new ObjectParameter("state_id", typeof(byte));
    
            var name_lawParameter = name_law != null ?
                new ObjectParameter("name_law", name_law) :
                new ObjectParameter("name_law", typeof(string));
    
            var head_nameParameter = head_name != null ?
                new ObjectParameter("head_name", head_name) :
                new ObjectParameter("head_name", typeof(string));
    
            var head_commentParameter = head_comment != null ?
                new ObjectParameter("head_comment", head_comment) :
                new ObjectParameter("head_comment", typeof(string));
    
            var head_phone_workParameter = head_phone_work != null ?
                new ObjectParameter("head_phone_work", head_phone_work) :
                new ObjectParameter("head_phone_work", typeof(string));
    
            var head_phone_homeParameter = head_phone_home != null ?
                new ObjectParameter("head_phone_home", head_phone_home) :
                new ObjectParameter("head_phone_home", typeof(string));
    
            var head_phone_mobileParameter = head_phone_mobile != null ?
                new ObjectParameter("head_phone_mobile", head_phone_mobile) :
                new ObjectParameter("head_phone_mobile", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("fax", fax) :
                new ObjectParameter("fax", typeof(string));
    
            var httpParameter = http != null ?
                new ObjectParameter("http", http) :
                new ObjectParameter("http", typeof(string));
    
            var head_emailParameter = head_email != null ?
                new ObjectParameter("head_email", head_email) :
                new ObjectParameter("head_email", typeof(string));
    
            var field_nameParameter = field_name != null ?
                new ObjectParameter("field_name", field_name) :
                new ObjectParameter("field_name", typeof(string));
    
            var field_commentParameter = field_comment != null ?
                new ObjectParameter("field_comment", field_comment) :
                new ObjectParameter("field_comment", typeof(string));
    
            var field_phone_workParameter = field_phone_work != null ?
                new ObjectParameter("field_phone_work", field_phone_work) :
                new ObjectParameter("field_phone_work", typeof(string));
    
            var field_phone_homeParameter = field_phone_home != null ?
                new ObjectParameter("field_phone_home", field_phone_home) :
                new ObjectParameter("field_phone_home", typeof(string));
    
            var field_phone_mobileParameter = field_phone_mobile != null ?
                new ObjectParameter("field_phone_mobile", field_phone_mobile) :
                new ObjectParameter("field_phone_mobile", typeof(string));
    
            var field_emailParameter = field_email != null ?
                new ObjectParameter("field_email", field_email) :
                new ObjectParameter("field_email", typeof(string));
    
            var inter_countParameter = inter_count.HasValue ?
                new ObjectParameter("inter_count", inter_count) :
                new ObjectParameter("inter_count", typeof(short));
    
            var address_factParameter = address_fact != null ?
                new ObjectParameter("address_fact", address_fact) :
                new ObjectParameter("address_fact", typeof(string));
    
            var address_lawParameter = address_law != null ?
                new ObjectParameter("address_law", address_law) :
                new ObjectParameter("address_law", typeof(string));
    
            var computer_countParameter = computer_count.HasValue ?
                new ObjectParameter("computer_count", computer_count) :
                new ObjectParameter("computer_count", typeof(short));
    
            var manager_countParameter = manager_count.HasValue ?
                new ObjectParameter("manager_count", manager_count) :
                new ObjectParameter("manager_count", typeof(short));
    
            var iNNParameter = iNN != null ?
                new ObjectParameter("INN", iNN) :
                new ObjectParameter("INN", typeof(string));
    
            var kPPParameter = kPP != null ?
                new ObjectParameter("KPP", kPP) :
                new ObjectParameter("KPP", typeof(string));
    
            var vATParameter = vAT.HasValue ?
                new ObjectParameter("VAT", vAT) :
                new ObjectParameter("VAT", typeof(bool));
    
            var vAT_argumentParameter = vAT_argument != null ?
                new ObjectParameter("VAT_argument", vAT_argument) :
                new ObjectParameter("VAT_argument", typeof(string));
    
            var recvisitsParameter = recvisits != null ?
                new ObjectParameter("recvisits", recvisits) :
                new ObjectParameter("recvisits", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var fin_headParameter = fin_head != null ?
                new ObjectParameter("fin_head", fin_head) :
                new ObjectParameter("fin_head", typeof(string));
    
            var fin_positionParameter = fin_position != null ?
                new ObjectParameter("fin_position", fin_position) :
                new ObjectParameter("fin_position", typeof(string));
    
            var work_onParameter = work_on != null ?
                new ObjectParameter("work_on", work_on) :
                new ObjectParameter("work_on", typeof(string));
    
            var ind_licenceParameter = ind_licence != null ?
                new ObjectParameter("ind_licence", ind_licence) :
                new ObjectParameter("ind_licence", typeof(string));
    
            var ind_taxParameter = ind_tax != null ?
                new ObjectParameter("ind_tax", ind_tax) :
                new ObjectParameter("ind_tax", typeof(string));
    
            var ind_innParameter = ind_inn != null ?
                new ObjectParameter("ind_inn", ind_inn) :
                new ObjectParameter("ind_inn", typeof(string));
    
            var ind_registerParameter = ind_register != null ?
                new ObjectParameter("ind_register", ind_register) :
                new ObjectParameter("ind_register", typeof(string));
    
            var desc_controlParameter = desc_control != null ?
                new ObjectParameter("desc_control", desc_control) :
                new ObjectParameter("desc_control", typeof(string));
    
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var folderParameter = folder != null ?
                new ObjectParameter("folder", folder) :
                new ObjectParameter("folder", typeof(string));
    
            var dictaphoneParameter = dictaphone.HasValue ?
                new ObjectParameter("dictaphone", dictaphone) :
                new ObjectParameter("dictaphone", typeof(int));
    
            var notebookParameter = notebook.HasValue ?
                new ObjectParameter("notebook", notebook) :
                new ObjectParameter("notebook", typeof(int));
    
            var computerParameter = computer.HasValue ?
                new ObjectParameter("computer", computer) :
                new ObjectParameter("computer", typeof(int));
    
            var pdaParameter = pda.HasValue ?
                new ObjectParameter("pda", pda) :
                new ObjectParameter("pda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_add", manager_idParameter, workplace_type_idParameter, name_factParameter, state_idParameter, name_lawParameter, head_nameParameter, head_commentParameter, head_phone_workParameter, head_phone_homeParameter, head_phone_mobileParameter, faxParameter, httpParameter, head_emailParameter, field_nameParameter, field_commentParameter, field_phone_workParameter, field_phone_homeParameter, field_phone_mobileParameter, field_emailParameter, inter_countParameter, address_factParameter, address_lawParameter, computer_countParameter, manager_countParameter, iNNParameter, kPPParameter, vATParameter, vAT_argumentParameter, recvisitsParameter, descriptionParameter, fin_headParameter, fin_positionParameter, work_onParameter, ind_licenceParameter, ind_taxParameter, ind_innParameter, ind_registerParameter, desc_controlParameter, loginParameter, passwordParameter, folderParameter, dictaphoneParameter, notebookParameter, computerParameter, pdaParameter);
        }
    
        public virtual int supervisor_agreement_add(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> supervisor_id, Nullable<byte> super_agree_type_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var super_agree_type_idParameter = super_agree_type_id.HasValue ?
                new ObjectParameter("super_agree_type_id", super_agree_type_id) :
                new ObjectParameter("super_agree_type_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_agreement_add", manager_idParameter, workplace_type_idParameter, supervisor_idParameter, super_agree_type_idParameter);
        }
    
        public virtual int supervisor_agreement_del(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> super_agree_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var super_agree_idParameter = super_agree_id.HasValue ?
                new ObjectParameter("super_agree_id", super_agree_id) :
                new ObjectParameter("super_agree_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_agreement_del", manager_idParameter, workplace_type_idParameter, super_agree_idParameter);
        }
    
        public virtual int supervisor_delete(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> supervisor_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_delete", manager_idParameter, workplace_type_idParameter, supervisor_idParameter);
        }
    
        public virtual int supervisor_event_add(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> supervisor_id, Nullable<System.DateTime> event_date, string text, string description)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var event_dateParameter = event_date.HasValue ?
                new ObjectParameter("event_date", event_date) :
                new ObjectParameter("event_date", typeof(System.DateTime));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_event_add", manager_idParameter, workplace_type_idParameter, supervisor_idParameter, event_dateParameter, textParameter, descriptionParameter);
        }
    
        public virtual int supervisor_event_delete(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> supervisor_event_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var supervisor_event_idParameter = supervisor_event_id.HasValue ?
                new ObjectParameter("supervisor_event_id", supervisor_event_id) :
                new ObjectParameter("supervisor_event_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_event_delete", manager_idParameter, workplace_type_idParameter, supervisor_event_idParameter);
        }
    
        public virtual int supervisor_event_update(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> supervisor_event_id, Nullable<System.DateTime> event_date, string text, string description)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var supervisor_event_idParameter = supervisor_event_id.HasValue ?
                new ObjectParameter("supervisor_event_id", supervisor_event_id) :
                new ObjectParameter("supervisor_event_id", typeof(int));
    
            var event_dateParameter = event_date.HasValue ?
                new ObjectParameter("event_date", event_date) :
                new ObjectParameter("event_date", typeof(System.DateTime));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_event_update", manager_idParameter, workplace_type_idParameter, supervisor_event_idParameter, event_dateParameter, textParameter, descriptionParameter);
        }
    
        public virtual int supervisor_place_add(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> supervisor_id, Nullable<int> terr_list_id, Nullable<byte> super_territory_type_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var terr_list_idParameter = terr_list_id.HasValue ?
                new ObjectParameter("terr_list_id", terr_list_id) :
                new ObjectParameter("terr_list_id", typeof(int));
    
            var super_territory_type_idParameter = super_territory_type_id.HasValue ?
                new ObjectParameter("super_territory_type_id", super_territory_type_id) :
                new ObjectParameter("super_territory_type_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_place_add", manager_idParameter, workplace_type_idParameter, supervisor_idParameter, terr_list_idParameter, super_territory_type_idParameter);
        }
    
        public virtual int supervisor_place_delete(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> super_place_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var super_place_idParameter = super_place_id.HasValue ?
                new ObjectParameter("super_place_id", super_place_id) :
                new ObjectParameter("super_place_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_place_delete", manager_idParameter, workplace_type_idParameter, super_place_idParameter);
        }
    
        public virtual int supervisor_place_update(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> super_place_id, Nullable<int> supervisor_id, Nullable<int> terr_list_id, Nullable<byte> super_territory_type_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var super_place_idParameter = super_place_id.HasValue ?
                new ObjectParameter("super_place_id", super_place_id) :
                new ObjectParameter("super_place_id", typeof(int));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var terr_list_idParameter = terr_list_id.HasValue ?
                new ObjectParameter("terr_list_id", terr_list_id) :
                new ObjectParameter("terr_list_id", typeof(int));
    
            var super_territory_type_idParameter = super_territory_type_id.HasValue ?
                new ObjectParameter("super_territory_type_id", super_territory_type_id) :
                new ObjectParameter("super_territory_type_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_place_update", manager_idParameter, workplace_type_idParameter, super_place_idParameter, supervisor_idParameter, terr_list_idParameter, super_territory_type_idParameter);
        }
    
        public virtual int supervisor_setstate(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<short> supervisor_id, Nullable<byte> catalogue_state_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(short));
    
            var catalogue_state_idParameter = catalogue_state_id.HasValue ?
                new ObjectParameter("catalogue_state_id", catalogue_state_id) :
                new ObjectParameter("catalogue_state_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_setstate", manager_idParameter, workplace_type_idParameter, supervisor_idParameter, catalogue_state_idParameter);
        }
    
        public virtual int supervisor_update(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> supervisor_id, string name_fact, Nullable<byte> state_id, string name_law, string head_name, string head_comment, string head_phone_work, string head_phone_home, string head_phone_mobile, string fax, string http, string head_email, string field_name, string field_comment, string field_phone_work, string field_phone_home, string field_phone_mobile, string field_email, Nullable<short> inter_count, string address_fact, string address_law, Nullable<short> computer_count, Nullable<short> manager_count, string iNN, string kPP, Nullable<bool> vAT, string vAT_argument, string recvisits, string description, string fin_head, string fin_position, string work_on, string ind_licence, string ind_tax, string ind_inn, string ind_register, string desc_control, string login, string password, string folder, Nullable<int> dictaphone, Nullable<int> notebook, Nullable<int> computer, Nullable<int> pda)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var name_factParameter = name_fact != null ?
                new ObjectParameter("name_fact", name_fact) :
                new ObjectParameter("name_fact", typeof(string));
    
            var state_idParameter = state_id.HasValue ?
                new ObjectParameter("state_id", state_id) :
                new ObjectParameter("state_id", typeof(byte));
    
            var name_lawParameter = name_law != null ?
                new ObjectParameter("name_law", name_law) :
                new ObjectParameter("name_law", typeof(string));
    
            var head_nameParameter = head_name != null ?
                new ObjectParameter("head_name", head_name) :
                new ObjectParameter("head_name", typeof(string));
    
            var head_commentParameter = head_comment != null ?
                new ObjectParameter("head_comment", head_comment) :
                new ObjectParameter("head_comment", typeof(string));
    
            var head_phone_workParameter = head_phone_work != null ?
                new ObjectParameter("head_phone_work", head_phone_work) :
                new ObjectParameter("head_phone_work", typeof(string));
    
            var head_phone_homeParameter = head_phone_home != null ?
                new ObjectParameter("head_phone_home", head_phone_home) :
                new ObjectParameter("head_phone_home", typeof(string));
    
            var head_phone_mobileParameter = head_phone_mobile != null ?
                new ObjectParameter("head_phone_mobile", head_phone_mobile) :
                new ObjectParameter("head_phone_mobile", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("fax", fax) :
                new ObjectParameter("fax", typeof(string));
    
            var httpParameter = http != null ?
                new ObjectParameter("http", http) :
                new ObjectParameter("http", typeof(string));
    
            var head_emailParameter = head_email != null ?
                new ObjectParameter("head_email", head_email) :
                new ObjectParameter("head_email", typeof(string));
    
            var field_nameParameter = field_name != null ?
                new ObjectParameter("field_name", field_name) :
                new ObjectParameter("field_name", typeof(string));
    
            var field_commentParameter = field_comment != null ?
                new ObjectParameter("field_comment", field_comment) :
                new ObjectParameter("field_comment", typeof(string));
    
            var field_phone_workParameter = field_phone_work != null ?
                new ObjectParameter("field_phone_work", field_phone_work) :
                new ObjectParameter("field_phone_work", typeof(string));
    
            var field_phone_homeParameter = field_phone_home != null ?
                new ObjectParameter("field_phone_home", field_phone_home) :
                new ObjectParameter("field_phone_home", typeof(string));
    
            var field_phone_mobileParameter = field_phone_mobile != null ?
                new ObjectParameter("field_phone_mobile", field_phone_mobile) :
                new ObjectParameter("field_phone_mobile", typeof(string));
    
            var field_emailParameter = field_email != null ?
                new ObjectParameter("field_email", field_email) :
                new ObjectParameter("field_email", typeof(string));
    
            var inter_countParameter = inter_count.HasValue ?
                new ObjectParameter("inter_count", inter_count) :
                new ObjectParameter("inter_count", typeof(short));
    
            var address_factParameter = address_fact != null ?
                new ObjectParameter("address_fact", address_fact) :
                new ObjectParameter("address_fact", typeof(string));
    
            var address_lawParameter = address_law != null ?
                new ObjectParameter("address_law", address_law) :
                new ObjectParameter("address_law", typeof(string));
    
            var computer_countParameter = computer_count.HasValue ?
                new ObjectParameter("computer_count", computer_count) :
                new ObjectParameter("computer_count", typeof(short));
    
            var manager_countParameter = manager_count.HasValue ?
                new ObjectParameter("manager_count", manager_count) :
                new ObjectParameter("manager_count", typeof(short));
    
            var iNNParameter = iNN != null ?
                new ObjectParameter("INN", iNN) :
                new ObjectParameter("INN", typeof(string));
    
            var kPPParameter = kPP != null ?
                new ObjectParameter("KPP", kPP) :
                new ObjectParameter("KPP", typeof(string));
    
            var vATParameter = vAT.HasValue ?
                new ObjectParameter("VAT", vAT) :
                new ObjectParameter("VAT", typeof(bool));
    
            var vAT_argumentParameter = vAT_argument != null ?
                new ObjectParameter("VAT_argument", vAT_argument) :
                new ObjectParameter("VAT_argument", typeof(string));
    
            var recvisitsParameter = recvisits != null ?
                new ObjectParameter("recvisits", recvisits) :
                new ObjectParameter("recvisits", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var fin_headParameter = fin_head != null ?
                new ObjectParameter("fin_head", fin_head) :
                new ObjectParameter("fin_head", typeof(string));
    
            var fin_positionParameter = fin_position != null ?
                new ObjectParameter("fin_position", fin_position) :
                new ObjectParameter("fin_position", typeof(string));
    
            var work_onParameter = work_on != null ?
                new ObjectParameter("work_on", work_on) :
                new ObjectParameter("work_on", typeof(string));
    
            var ind_licenceParameter = ind_licence != null ?
                new ObjectParameter("ind_licence", ind_licence) :
                new ObjectParameter("ind_licence", typeof(string));
    
            var ind_taxParameter = ind_tax != null ?
                new ObjectParameter("ind_tax", ind_tax) :
                new ObjectParameter("ind_tax", typeof(string));
    
            var ind_innParameter = ind_inn != null ?
                new ObjectParameter("ind_inn", ind_inn) :
                new ObjectParameter("ind_inn", typeof(string));
    
            var ind_registerParameter = ind_register != null ?
                new ObjectParameter("ind_register", ind_register) :
                new ObjectParameter("ind_register", typeof(string));
    
            var desc_controlParameter = desc_control != null ?
                new ObjectParameter("desc_control", desc_control) :
                new ObjectParameter("desc_control", typeof(string));
    
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var folderParameter = folder != null ?
                new ObjectParameter("folder", folder) :
                new ObjectParameter("folder", typeof(string));
    
            var dictaphoneParameter = dictaphone.HasValue ?
                new ObjectParameter("dictaphone", dictaphone) :
                new ObjectParameter("dictaphone", typeof(int));
    
            var notebookParameter = notebook.HasValue ?
                new ObjectParameter("notebook", notebook) :
                new ObjectParameter("notebook", typeof(int));
    
            var computerParameter = computer.HasValue ?
                new ObjectParameter("computer", computer) :
                new ObjectParameter("computer", typeof(int));
    
            var pdaParameter = pda.HasValue ?
                new ObjectParameter("pda", pda) :
                new ObjectParameter("pda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_update", manager_idParameter, workplace_type_idParameter, supervisor_idParameter, name_factParameter, state_idParameter, name_lawParameter, head_nameParameter, head_commentParameter, head_phone_workParameter, head_phone_homeParameter, head_phone_mobileParameter, faxParameter, httpParameter, head_emailParameter, field_nameParameter, field_commentParameter, field_phone_workParameter, field_phone_homeParameter, field_phone_mobileParameter, field_emailParameter, inter_countParameter, address_factParameter, address_lawParameter, computer_countParameter, manager_countParameter, iNNParameter, kPPParameter, vATParameter, vAT_argumentParameter, recvisitsParameter, descriptionParameter, fin_headParameter, fin_positionParameter, work_onParameter, ind_licenceParameter, ind_taxParameter, ind_innParameter, ind_registerParameter, desc_controlParameter, loginParameter, passwordParameter, folderParameter, dictaphoneParameter, notebookParameter, computerParameter, pdaParameter);
        }
    
        public virtual int supervisor_work_add(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> supervisor_id, Nullable<byte> super_work_type_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var super_work_type_idParameter = super_work_type_id.HasValue ?
                new ObjectParameter("super_work_type_id", super_work_type_id) :
                new ObjectParameter("super_work_type_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_work_add", manager_idParameter, workplace_type_idParameter, supervisor_idParameter, super_work_type_idParameter);
        }
    
        public virtual int supervisor_work_del(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> super_work_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var super_work_idParameter = super_work_id.HasValue ?
                new ObjectParameter("super_work_id", super_work_id) :
                new ObjectParameter("super_work_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_work_del", manager_idParameter, workplace_type_idParameter, super_work_idParameter);
        }
    
        public virtual int supervisor_work_update(Nullable<int> manager_id, Nullable<byte> workplace_type_id, Nullable<int> super_work_id, Nullable<int> supervisor_id, Nullable<byte> super_work_type_id)
        {
            var manager_idParameter = manager_id.HasValue ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(int));
    
            var workplace_type_idParameter = workplace_type_id.HasValue ?
                new ObjectParameter("workplace_type_id", workplace_type_id) :
                new ObjectParameter("workplace_type_id", typeof(byte));
    
            var super_work_idParameter = super_work_id.HasValue ?
                new ObjectParameter("super_work_id", super_work_id) :
                new ObjectParameter("super_work_id", typeof(int));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var super_work_type_idParameter = super_work_type_id.HasValue ?
                new ObjectParameter("super_work_type_id", super_work_type_id) :
                new ObjectParameter("super_work_type_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("supervisor_work_update", manager_idParameter, workplace_type_idParameter, super_work_idParameter, supervisor_idParameter, super_work_type_idParameter);
        }
    
        public virtual ObjectResult<router_super_list_Result> router_super_list(Nullable<byte> place_type, Nullable<int> place_id, Nullable<byte> state_id, Nullable<byte> work_type_id)
        {
            var place_typeParameter = place_type.HasValue ?
                new ObjectParameter("place_type", place_type) :
                new ObjectParameter("place_type", typeof(byte));
    
            var place_idParameter = place_id.HasValue ?
                new ObjectParameter("place_id", place_id) :
                new ObjectParameter("place_id", typeof(int));
    
            var state_idParameter = state_id.HasValue ?
                new ObjectParameter("state_id", state_id) :
                new ObjectParameter("state_id", typeof(byte));
    
            var work_type_idParameter = work_type_id.HasValue ?
                new ObjectParameter("work_type_id", work_type_id) :
                new ObjectParameter("work_type_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<router_super_list_Result>("router_super_list", place_typeParameter, place_idParameter, state_idParameter, work_type_idParameter);
        }
    
        public virtual int router_manager_add(Nullable<int> supervisor_id, string name, string phone, string email, string desc)
        {
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_manager_add", supervisor_idParameter, nameParameter, phoneParameter, emailParameter, descParameter);
        }
    
        public virtual int router_manager_delete(Nullable<int> super_manager_id)
        {
            var super_manager_idParameter = super_manager_id.HasValue ?
                new ObjectParameter("super_manager_id", super_manager_id) :
                new ObjectParameter("super_manager_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_manager_delete", super_manager_idParameter);
        }
    
        public virtual int router_manager_update(Nullable<int> super_manager_id, Nullable<int> supervisor_id, string name, string phone, string email, string desc)
        {
            var super_manager_idParameter = super_manager_id.HasValue ?
                new ObjectParameter("super_manager_id", super_manager_id) :
                new ObjectParameter("super_manager_id", typeof(int));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_manager_update", super_manager_idParameter, supervisor_idParameter, nameParameter, phoneParameter, emailParameter, descParameter);
        }
    
        public virtual int router_supervisor_delete(Nullable<int> supervisor_id)
        {
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_supervisor_delete", supervisor_idParameter);
        }
    
        public virtual int router_supervisor_place_delete(Nullable<int> super_place_id)
        {
            var super_place_idParameter = super_place_id.HasValue ?
                new ObjectParameter("super_place_id", super_place_id) :
                new ObjectParameter("super_place_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_supervisor_place_delete", super_place_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> router_supervisor_add(string name_fact, Nullable<byte> state_id, string name_law, string head_name, string head_comment, string head_phone_work, string head_phone_home, string head_phone_mobile, string fax, string http, string head_email, string field_name, string field_comment, string field_phone_work, string field_phone_home, string field_phone_mobile, string field_email, Nullable<short> inter_count, string address_fact, string address_law, Nullable<short> computer_count, Nullable<short> manager_count, string iNN, string kPP, Nullable<bool> vAT, string vAT_argument, string recvisits, string description, string fin_head, string fin_position, string work_on, string ind_licence, string ind_tax, string ind_inn, string ind_register, string desc_control, string login, string password, string folder, Nullable<int> dictaphone, Nullable<int> notebook, Nullable<int> computer, Nullable<int> pda)
        {
            var name_factParameter = name_fact != null ?
                new ObjectParameter("name_fact", name_fact) :
                new ObjectParameter("name_fact", typeof(string));
    
            var state_idParameter = state_id.HasValue ?
                new ObjectParameter("state_id", state_id) :
                new ObjectParameter("state_id", typeof(byte));
    
            var name_lawParameter = name_law != null ?
                new ObjectParameter("name_law", name_law) :
                new ObjectParameter("name_law", typeof(string));
    
            var head_nameParameter = head_name != null ?
                new ObjectParameter("head_name", head_name) :
                new ObjectParameter("head_name", typeof(string));
    
            var head_commentParameter = head_comment != null ?
                new ObjectParameter("head_comment", head_comment) :
                new ObjectParameter("head_comment", typeof(string));
    
            var head_phone_workParameter = head_phone_work != null ?
                new ObjectParameter("head_phone_work", head_phone_work) :
                new ObjectParameter("head_phone_work", typeof(string));
    
            var head_phone_homeParameter = head_phone_home != null ?
                new ObjectParameter("head_phone_home", head_phone_home) :
                new ObjectParameter("head_phone_home", typeof(string));
    
            var head_phone_mobileParameter = head_phone_mobile != null ?
                new ObjectParameter("head_phone_mobile", head_phone_mobile) :
                new ObjectParameter("head_phone_mobile", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("fax", fax) :
                new ObjectParameter("fax", typeof(string));
    
            var httpParameter = http != null ?
                new ObjectParameter("http", http) :
                new ObjectParameter("http", typeof(string));
    
            var head_emailParameter = head_email != null ?
                new ObjectParameter("head_email", head_email) :
                new ObjectParameter("head_email", typeof(string));
    
            var field_nameParameter = field_name != null ?
                new ObjectParameter("field_name", field_name) :
                new ObjectParameter("field_name", typeof(string));
    
            var field_commentParameter = field_comment != null ?
                new ObjectParameter("field_comment", field_comment) :
                new ObjectParameter("field_comment", typeof(string));
    
            var field_phone_workParameter = field_phone_work != null ?
                new ObjectParameter("field_phone_work", field_phone_work) :
                new ObjectParameter("field_phone_work", typeof(string));
    
            var field_phone_homeParameter = field_phone_home != null ?
                new ObjectParameter("field_phone_home", field_phone_home) :
                new ObjectParameter("field_phone_home", typeof(string));
    
            var field_phone_mobileParameter = field_phone_mobile != null ?
                new ObjectParameter("field_phone_mobile", field_phone_mobile) :
                new ObjectParameter("field_phone_mobile", typeof(string));
    
            var field_emailParameter = field_email != null ?
                new ObjectParameter("field_email", field_email) :
                new ObjectParameter("field_email", typeof(string));
    
            var inter_countParameter = inter_count.HasValue ?
                new ObjectParameter("inter_count", inter_count) :
                new ObjectParameter("inter_count", typeof(short));
    
            var address_factParameter = address_fact != null ?
                new ObjectParameter("address_fact", address_fact) :
                new ObjectParameter("address_fact", typeof(string));
    
            var address_lawParameter = address_law != null ?
                new ObjectParameter("address_law", address_law) :
                new ObjectParameter("address_law", typeof(string));
    
            var computer_countParameter = computer_count.HasValue ?
                new ObjectParameter("computer_count", computer_count) :
                new ObjectParameter("computer_count", typeof(short));
    
            var manager_countParameter = manager_count.HasValue ?
                new ObjectParameter("manager_count", manager_count) :
                new ObjectParameter("manager_count", typeof(short));
    
            var iNNParameter = iNN != null ?
                new ObjectParameter("INN", iNN) :
                new ObjectParameter("INN", typeof(string));
    
            var kPPParameter = kPP != null ?
                new ObjectParameter("KPP", kPP) :
                new ObjectParameter("KPP", typeof(string));
    
            var vATParameter = vAT.HasValue ?
                new ObjectParameter("VAT", vAT) :
                new ObjectParameter("VAT", typeof(bool));
    
            var vAT_argumentParameter = vAT_argument != null ?
                new ObjectParameter("VAT_argument", vAT_argument) :
                new ObjectParameter("VAT_argument", typeof(string));
    
            var recvisitsParameter = recvisits != null ?
                new ObjectParameter("recvisits", recvisits) :
                new ObjectParameter("recvisits", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var fin_headParameter = fin_head != null ?
                new ObjectParameter("fin_head", fin_head) :
                new ObjectParameter("fin_head", typeof(string));
    
            var fin_positionParameter = fin_position != null ?
                new ObjectParameter("fin_position", fin_position) :
                new ObjectParameter("fin_position", typeof(string));
    
            var work_onParameter = work_on != null ?
                new ObjectParameter("work_on", work_on) :
                new ObjectParameter("work_on", typeof(string));
    
            var ind_licenceParameter = ind_licence != null ?
                new ObjectParameter("ind_licence", ind_licence) :
                new ObjectParameter("ind_licence", typeof(string));
    
            var ind_taxParameter = ind_tax != null ?
                new ObjectParameter("ind_tax", ind_tax) :
                new ObjectParameter("ind_tax", typeof(string));
    
            var ind_innParameter = ind_inn != null ?
                new ObjectParameter("ind_inn", ind_inn) :
                new ObjectParameter("ind_inn", typeof(string));
    
            var ind_registerParameter = ind_register != null ?
                new ObjectParameter("ind_register", ind_register) :
                new ObjectParameter("ind_register", typeof(string));
    
            var desc_controlParameter = desc_control != null ?
                new ObjectParameter("desc_control", desc_control) :
                new ObjectParameter("desc_control", typeof(string));
    
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var folderParameter = folder != null ?
                new ObjectParameter("folder", folder) :
                new ObjectParameter("folder", typeof(string));
    
            var dictaphoneParameter = dictaphone.HasValue ?
                new ObjectParameter("dictaphone", dictaphone) :
                new ObjectParameter("dictaphone", typeof(int));
    
            var notebookParameter = notebook.HasValue ?
                new ObjectParameter("notebook", notebook) :
                new ObjectParameter("notebook", typeof(int));
    
            var computerParameter = computer.HasValue ?
                new ObjectParameter("computer", computer) :
                new ObjectParameter("computer", typeof(int));
    
            var pdaParameter = pda.HasValue ?
                new ObjectParameter("pda", pda) :
                new ObjectParameter("pda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("router_supervisor_add", name_factParameter, state_idParameter, name_lawParameter, head_nameParameter, head_commentParameter, head_phone_workParameter, head_phone_homeParameter, head_phone_mobileParameter, faxParameter, httpParameter, head_emailParameter, field_nameParameter, field_commentParameter, field_phone_workParameter, field_phone_homeParameter, field_phone_mobileParameter, field_emailParameter, inter_countParameter, address_factParameter, address_lawParameter, computer_countParameter, manager_countParameter, iNNParameter, kPPParameter, vATParameter, vAT_argumentParameter, recvisitsParameter, descriptionParameter, fin_headParameter, fin_positionParameter, work_onParameter, ind_licenceParameter, ind_taxParameter, ind_innParameter, ind_registerParameter, desc_controlParameter, loginParameter, passwordParameter, folderParameter, dictaphoneParameter, notebookParameter, computerParameter, pdaParameter);
        }
    
        public virtual int router_supervisor_place_add(Nullable<int> supervisor_id, Nullable<int> territory_id, Nullable<byte> super_territory_type_id, Nullable<byte> super_place_type_id)
        {
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var territory_idParameter = territory_id.HasValue ?
                new ObjectParameter("territory_id", territory_id) :
                new ObjectParameter("territory_id", typeof(int));
    
            var super_territory_type_idParameter = super_territory_type_id.HasValue ?
                new ObjectParameter("super_territory_type_id", super_territory_type_id) :
                new ObjectParameter("super_territory_type_id", typeof(byte));
    
            var super_place_type_idParameter = super_place_type_id.HasValue ?
                new ObjectParameter("super_place_type_id", super_place_type_id) :
                new ObjectParameter("super_place_type_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_supervisor_place_add", supervisor_idParameter, territory_idParameter, super_territory_type_idParameter, super_place_type_idParameter);
        }
    
        public virtual int router_supervisor_work_add(Nullable<int> supervisor_id, Nullable<byte> super_work_type_id)
        {
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var super_work_type_idParameter = super_work_type_id.HasValue ?
                new ObjectParameter("super_work_type_id", super_work_type_id) :
                new ObjectParameter("super_work_type_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_supervisor_work_add", supervisor_idParameter, super_work_type_idParameter);
        }
    
        public virtual int router_supervisor_work_del(Nullable<int> super_work_id)
        {
            var super_work_idParameter = super_work_id.HasValue ?
                new ObjectParameter("super_work_id", super_work_id) :
                new ObjectParameter("super_work_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_supervisor_work_del", super_work_idParameter);
        }
    
        public virtual int router_supervisor_place_update(Nullable<int> super_place_id, Nullable<int> supervisor_id, Nullable<int> territory_id, Nullable<int> super_place_type_id, Nullable<byte> super_territory_type_id)
        {
            var super_place_idParameter = super_place_id.HasValue ?
                new ObjectParameter("super_place_id", super_place_id) :
                new ObjectParameter("super_place_id", typeof(int));
    
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var territory_idParameter = territory_id.HasValue ?
                new ObjectParameter("territory_id", territory_id) :
                new ObjectParameter("territory_id", typeof(int));
    
            var super_place_type_idParameter = super_place_type_id.HasValue ?
                new ObjectParameter("super_place_type_id", super_place_type_id) :
                new ObjectParameter("super_place_type_id", typeof(int));
    
            var super_territory_type_idParameter = super_territory_type_id.HasValue ?
                new ObjectParameter("super_territory_type_id", super_territory_type_id) :
                new ObjectParameter("super_territory_type_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_supervisor_place_update", super_place_idParameter, supervisor_idParameter, territory_idParameter, super_place_type_idParameter, super_territory_type_idParameter);
        }
    
        public virtual int router_supervisor_update(Nullable<int> supervisor_id, string name_fact, Nullable<byte> state_id, string name_law, string head_name, string head_comment, string head_phone_work, string head_phone_home, string head_phone_mobile, string fax, string http, string head_email, string field_name, string field_comment, string field_phone_work, string field_phone_home, string field_phone_mobile, string field_email, Nullable<short> inter_count, string address_fact, string address_law, Nullable<short> computer_count, Nullable<short> manager_count, string iNN, string kPP, Nullable<bool> vAT, string vAT_argument, string recvisits, string description, string fin_head, string fin_position, string work_on, string ind_licence, string ind_tax, string ind_inn, string ind_register, string desc_control, string login, string password, string folder, Nullable<int> dictaphone, Nullable<int> notebook, Nullable<int> computer, Nullable<int> pda)
        {
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var name_factParameter = name_fact != null ?
                new ObjectParameter("name_fact", name_fact) :
                new ObjectParameter("name_fact", typeof(string));
    
            var state_idParameter = state_id.HasValue ?
                new ObjectParameter("state_id", state_id) :
                new ObjectParameter("state_id", typeof(byte));
    
            var name_lawParameter = name_law != null ?
                new ObjectParameter("name_law", name_law) :
                new ObjectParameter("name_law", typeof(string));
    
            var head_nameParameter = head_name != null ?
                new ObjectParameter("head_name", head_name) :
                new ObjectParameter("head_name", typeof(string));
    
            var head_commentParameter = head_comment != null ?
                new ObjectParameter("head_comment", head_comment) :
                new ObjectParameter("head_comment", typeof(string));
    
            var head_phone_workParameter = head_phone_work != null ?
                new ObjectParameter("head_phone_work", head_phone_work) :
                new ObjectParameter("head_phone_work", typeof(string));
    
            var head_phone_homeParameter = head_phone_home != null ?
                new ObjectParameter("head_phone_home", head_phone_home) :
                new ObjectParameter("head_phone_home", typeof(string));
    
            var head_phone_mobileParameter = head_phone_mobile != null ?
                new ObjectParameter("head_phone_mobile", head_phone_mobile) :
                new ObjectParameter("head_phone_mobile", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("fax", fax) :
                new ObjectParameter("fax", typeof(string));
    
            var httpParameter = http != null ?
                new ObjectParameter("http", http) :
                new ObjectParameter("http", typeof(string));
    
            var head_emailParameter = head_email != null ?
                new ObjectParameter("head_email", head_email) :
                new ObjectParameter("head_email", typeof(string));
    
            var field_nameParameter = field_name != null ?
                new ObjectParameter("field_name", field_name) :
                new ObjectParameter("field_name", typeof(string));
    
            var field_commentParameter = field_comment != null ?
                new ObjectParameter("field_comment", field_comment) :
                new ObjectParameter("field_comment", typeof(string));
    
            var field_phone_workParameter = field_phone_work != null ?
                new ObjectParameter("field_phone_work", field_phone_work) :
                new ObjectParameter("field_phone_work", typeof(string));
    
            var field_phone_homeParameter = field_phone_home != null ?
                new ObjectParameter("field_phone_home", field_phone_home) :
                new ObjectParameter("field_phone_home", typeof(string));
    
            var field_phone_mobileParameter = field_phone_mobile != null ?
                new ObjectParameter("field_phone_mobile", field_phone_mobile) :
                new ObjectParameter("field_phone_mobile", typeof(string));
    
            var field_emailParameter = field_email != null ?
                new ObjectParameter("field_email", field_email) :
                new ObjectParameter("field_email", typeof(string));
    
            var inter_countParameter = inter_count.HasValue ?
                new ObjectParameter("inter_count", inter_count) :
                new ObjectParameter("inter_count", typeof(short));
    
            var address_factParameter = address_fact != null ?
                new ObjectParameter("address_fact", address_fact) :
                new ObjectParameter("address_fact", typeof(string));
    
            var address_lawParameter = address_law != null ?
                new ObjectParameter("address_law", address_law) :
                new ObjectParameter("address_law", typeof(string));
    
            var computer_countParameter = computer_count.HasValue ?
                new ObjectParameter("computer_count", computer_count) :
                new ObjectParameter("computer_count", typeof(short));
    
            var manager_countParameter = manager_count.HasValue ?
                new ObjectParameter("manager_count", manager_count) :
                new ObjectParameter("manager_count", typeof(short));
    
            var iNNParameter = iNN != null ?
                new ObjectParameter("INN", iNN) :
                new ObjectParameter("INN", typeof(string));
    
            var kPPParameter = kPP != null ?
                new ObjectParameter("KPP", kPP) :
                new ObjectParameter("KPP", typeof(string));
    
            var vATParameter = vAT.HasValue ?
                new ObjectParameter("VAT", vAT) :
                new ObjectParameter("VAT", typeof(bool));
    
            var vAT_argumentParameter = vAT_argument != null ?
                new ObjectParameter("VAT_argument", vAT_argument) :
                new ObjectParameter("VAT_argument", typeof(string));
    
            var recvisitsParameter = recvisits != null ?
                new ObjectParameter("recvisits", recvisits) :
                new ObjectParameter("recvisits", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var fin_headParameter = fin_head != null ?
                new ObjectParameter("fin_head", fin_head) :
                new ObjectParameter("fin_head", typeof(string));
    
            var fin_positionParameter = fin_position != null ?
                new ObjectParameter("fin_position", fin_position) :
                new ObjectParameter("fin_position", typeof(string));
    
            var work_onParameter = work_on != null ?
                new ObjectParameter("work_on", work_on) :
                new ObjectParameter("work_on", typeof(string));
    
            var ind_licenceParameter = ind_licence != null ?
                new ObjectParameter("ind_licence", ind_licence) :
                new ObjectParameter("ind_licence", typeof(string));
    
            var ind_taxParameter = ind_tax != null ?
                new ObjectParameter("ind_tax", ind_tax) :
                new ObjectParameter("ind_tax", typeof(string));
    
            var ind_innParameter = ind_inn != null ?
                new ObjectParameter("ind_inn", ind_inn) :
                new ObjectParameter("ind_inn", typeof(string));
    
            var ind_registerParameter = ind_register != null ?
                new ObjectParameter("ind_register", ind_register) :
                new ObjectParameter("ind_register", typeof(string));
    
            var desc_controlParameter = desc_control != null ?
                new ObjectParameter("desc_control", desc_control) :
                new ObjectParameter("desc_control", typeof(string));
    
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var folderParameter = folder != null ?
                new ObjectParameter("folder", folder) :
                new ObjectParameter("folder", typeof(string));
    
            var dictaphoneParameter = dictaphone.HasValue ?
                new ObjectParameter("dictaphone", dictaphone) :
                new ObjectParameter("dictaphone", typeof(int));
    
            var notebookParameter = notebook.HasValue ?
                new ObjectParameter("notebook", notebook) :
                new ObjectParameter("notebook", typeof(int));
    
            var computerParameter = computer.HasValue ?
                new ObjectParameter("computer", computer) :
                new ObjectParameter("computer", typeof(int));
    
            var pdaParameter = pda.HasValue ?
                new ObjectParameter("pda", pda) :
                new ObjectParameter("pda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_supervisor_update", supervisor_idParameter, name_factParameter, state_idParameter, name_lawParameter, head_nameParameter, head_commentParameter, head_phone_workParameter, head_phone_homeParameter, head_phone_mobileParameter, faxParameter, httpParameter, head_emailParameter, field_nameParameter, field_commentParameter, field_phone_workParameter, field_phone_homeParameter, field_phone_mobileParameter, field_emailParameter, inter_countParameter, address_factParameter, address_lawParameter, computer_countParameter, manager_countParameter, iNNParameter, kPPParameter, vATParameter, vAT_argumentParameter, recvisitsParameter, descriptionParameter, fin_headParameter, fin_positionParameter, work_onParameter, ind_licenceParameter, ind_taxParameter, ind_innParameter, ind_registerParameter, desc_controlParameter, loginParameter, passwordParameter, folderParameter, dictaphoneParameter, notebookParameter, computerParameter, pdaParameter);
        }
    
        public virtual int router_supervisor_agreement_add(Nullable<int> supervisor_id, Nullable<byte> super_agree_type_id)
        {
            var supervisor_idParameter = supervisor_id.HasValue ?
                new ObjectParameter("supervisor_id", supervisor_id) :
                new ObjectParameter("supervisor_id", typeof(int));
    
            var super_agree_type_idParameter = super_agree_type_id.HasValue ?
                new ObjectParameter("super_agree_type_id", super_agree_type_id) :
                new ObjectParameter("super_agree_type_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_supervisor_agreement_add", supervisor_idParameter, super_agree_type_idParameter);
        }
    
        public virtual int router_supervisor_agreement_del(Nullable<int> super_agree_id)
        {
            var super_agree_idParameter = super_agree_id.HasValue ?
                new ObjectParameter("super_agree_id", super_agree_id) :
                new ObjectParameter("super_agree_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("router_supervisor_agreement_del", super_agree_idParameter);
        }
    }
}
