//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_territories_v
    {
        public int id { get; set; }
        public string terr_list_id { get; set; }
        public int supervisor_id { get; set; }
        public byte super_territory_type_id { get; set; }
    }
}
