//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_v
    {
        public int id { get; set; }
        public string name_fact { get; set; }
        public string name_law { get; set; }
        public string head_name { get; set; }
        public string head_comment { get; set; }
        public string head_phone_work { get; set; }
        public string head_phone_home { get; set; }
        public string head_phone_mobile { get; set; }
        public string fax { get; set; }
        public string http { get; set; }
        public string head_email { get; set; }
        public string field_name { get; set; }
        public string field_comment { get; set; }
        public string field_phone_work { get; set; }
        public string field_phone_home { get; set; }
        public string field_phone_mobile { get; set; }
        public string field_email { get; set; }
        public Nullable<short> inter_count { get; set; }
        public string address_fact { get; set; }
        public string address_law { get; set; }
        public Nullable<short> computer_count { get; set; }
        public Nullable<short> manager_count { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public Nullable<bool> VAT { get; set; }
        public string VAT_argument { get; set; }
        public string recvisits { get; set; }
        public string description { get; set; }
        public string fin_head { get; set; }
        public string fin_position { get; set; }
        public string work_on { get; set; }
        public string ind_licence { get; set; }
        public string ind_tax { get; set; }
        public string ind_inn { get; set; }
        public string ind_register { get; set; }
        public string desc_control { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string folder { get; set; }
        public Nullable<int> dictaphone { get; set; }
        public Nullable<int> notebook { get; set; }
        public Nullable<int> computer { get; set; }
        public Nullable<int> pda { get; set; }
        public Nullable<byte> state_id { get; set; }
    }
}
