//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_works
    {
        public int super_work_id { get; set; }
        public int supervisor_id { get; set; }
        public byte super_work_type_id { get; set; }
    
        public virtual super_work_types super_work_types { get; set; }
        public virtual supervisors supervisors { get; set; }
    }
}
