//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_states
    {
        public super_states()
        {
            this.super_properties = new HashSet<super_properties>();
        }
    
        public byte super_state_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<super_properties> super_properties { get; set; }
    }
}
