//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_territory_types
    {
        public super_territory_types()
        {
            this.super_places = new HashSet<super_places>();
        }
    
        public byte super_territory_type_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<super_places> super_places { get; set; }
    }
}
