//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_agree_types
    {
        public super_agree_types()
        {
            this.super_agreements = new HashSet<super_agreements>();
        }
    
        public byte super_agree_type_id { get; set; }
        public string agree_name { get; set; }
    
        public virtual ICollection<super_agreements> super_agreements { get; set; }
    }
}
