//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_agreements
    {
        public int super_agree_id { get; set; }
        public int supervisor_id { get; set; }
        public byte super_agree_type_id { get; set; }
    
        public virtual super_agree_types super_agree_types { get; set; }
        public virtual supervisors supervisors { get; set; }
    }
}
