//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_places
    {
        public int super_place_id { get; set; }
        public int supervisor_id { get; set; }
        public int territory_id { get; set; }
        public byte super_territory_type_id { get; set; }
        public byte super_place_type_id { get; set; }
    
        public virtual super_place_types super_place_types { get; set; }
        public virtual super_territory_types super_territory_types { get; set; }
        public virtual supervisors supervisors { get; set; }
    }
}
