//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_properties
    {
        public int super_property_id { get; set; }
        public int supervisor_id { get; set; }
        public byte super_state_id { get; set; }
        public int manager_id { get; set; }
        public System.DateTime change_date { get; set; }
    
        public virtual super_states super_states { get; set; }
        public virtual supervisors supervisors { get; set; }
    }
}
