//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_work_types
    {
        public super_work_types()
        {
            this.super_works = new HashSet<super_works>();
        }
    
        public byte super_work_type_id { get; set; }
        public string name { get; set; }
        public byte ord { get; set; }
    
        public virtual ICollection<super_works> super_works { get; set; }
    }
}
