//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_territories_show_v
    {
        public int id { get; set; }
        public string super_place_name { get; set; }
        public int supervisor_id { get; set; }
        public string super_territory_type { get; set; }
        public string name_fact { get; set; }
        public string head_name { get; set; }
        public string head_phone_work { get; set; }
        public string head_email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<bool> edit { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<bool> canstate { get; set; }
        public byte super_territory_type_id { get; set; }
        public string terr_list_id { get; set; }
        public Nullable<byte> state_id { get; set; }
        public byte super_work_type_id { get; set; }
        public Nullable<int> computer { get; set; }
    }
}
