//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuperDetails", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    public partial class SuperDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressFactField;
        
        private string AddressLawField;
        
        private Data.Place[] BrigadesField;
        
        private int ComputerField;
        
        private int ComputerCountField;
        
        private string DescControlField;
        
        private string DescriptionField;
        
        private int DictaphoneField;
        
        private string FaxField;
        
        private string FieldCommentField;
        
        private string FieldEmailField;
        
        private string FieldNameField;
        
        private string FieldPhoneHomeField;
        
        private string FieldPhoneMobileField;
        
        private string FieldPhoneWorkField;
        
        private string FinHeadField;
        
        private string FinPositionField;
        
        private string FolderField;
        
        private string HeadCommentField;
        
        private string HeadEmailField;
        
        private string HeadNameField;
        
        private string HeadPhoneHomeField;
        
        private string HeadPhoneMobileField;
        
        private string HeadPhoneWorkField;
        
        private string HttpField;
        
        private string INNField;
        
        private int IdField;
        
        private string IndInnField;
        
        private string IndLicenseField;
        
        private string IndRegisterField;
        
        private string IndTaxField;
        
        private int InterCountField;
        
        private string KPPField;
        
        private Data.Place[] LeaveField;
        
        private string LoginField;
        
        private int ManagerCountField;
        
        private string NameFactField;
        
        private string NameLawField;
        
        private int NotebookField;
        
        private string PasswordField;
        
        private int PdaField;
        
        private Data.Place PlaceIdField;
        
        private string RecvisitsField;
        
        private int StateIdField;
        
        private bool VATField;
        
        private string VAT_ArgumentField;
        
        private string WorkOnField;
        
        private Data.Works[] WorksField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressFact
        {
            get
            {
                return this.AddressFactField;
            }
            set
            {
                this.AddressFactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLaw
        {
            get
            {
                return this.AddressLawField;
            }
            set
            {
                this.AddressLawField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Data.Place[] Brigades
        {
            get
            {
                return this.BrigadesField;
            }
            set
            {
                this.BrigadesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Computer
        {
            get
            {
                return this.ComputerField;
            }
            set
            {
                this.ComputerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComputerCount
        {
            get
            {
                return this.ComputerCountField;
            }
            set
            {
                this.ComputerCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescControl
        {
            get
            {
                return this.DescControlField;
            }
            set
            {
                this.DescControlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dictaphone
        {
            get
            {
                return this.DictaphoneField;
            }
            set
            {
                this.DictaphoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldComment
        {
            get
            {
                return this.FieldCommentField;
            }
            set
            {
                this.FieldCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldEmail
        {
            get
            {
                return this.FieldEmailField;
            }
            set
            {
                this.FieldEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName
        {
            get
            {
                return this.FieldNameField;
            }
            set
            {
                this.FieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldPhoneHome
        {
            get
            {
                return this.FieldPhoneHomeField;
            }
            set
            {
                this.FieldPhoneHomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldPhoneMobile
        {
            get
            {
                return this.FieldPhoneMobileField;
            }
            set
            {
                this.FieldPhoneMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldPhoneWork
        {
            get
            {
                return this.FieldPhoneWorkField;
            }
            set
            {
                this.FieldPhoneWorkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinHead
        {
            get
            {
                return this.FinHeadField;
            }
            set
            {
                this.FinHeadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinPosition
        {
            get
            {
                return this.FinPositionField;
            }
            set
            {
                this.FinPositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folder
        {
            get
            {
                return this.FolderField;
            }
            set
            {
                this.FolderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadComment
        {
            get
            {
                return this.HeadCommentField;
            }
            set
            {
                this.HeadCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadEmail
        {
            get
            {
                return this.HeadEmailField;
            }
            set
            {
                this.HeadEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadName
        {
            get
            {
                return this.HeadNameField;
            }
            set
            {
                this.HeadNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadPhoneHome
        {
            get
            {
                return this.HeadPhoneHomeField;
            }
            set
            {
                this.HeadPhoneHomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadPhoneMobile
        {
            get
            {
                return this.HeadPhoneMobileField;
            }
            set
            {
                this.HeadPhoneMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadPhoneWork
        {
            get
            {
                return this.HeadPhoneWorkField;
            }
            set
            {
                this.HeadPhoneWorkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Http
        {
            get
            {
                return this.HttpField;
            }
            set
            {
                this.HttpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INN
        {
            get
            {
                return this.INNField;
            }
            set
            {
                this.INNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndInn
        {
            get
            {
                return this.IndInnField;
            }
            set
            {
                this.IndInnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndLicense
        {
            get
            {
                return this.IndLicenseField;
            }
            set
            {
                this.IndLicenseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndRegister
        {
            get
            {
                return this.IndRegisterField;
            }
            set
            {
                this.IndRegisterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndTax
        {
            get
            {
                return this.IndTaxField;
            }
            set
            {
                this.IndTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InterCount
        {
            get
            {
                return this.InterCountField;
            }
            set
            {
                this.InterCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KPP
        {
            get
            {
                return this.KPPField;
            }
            set
            {
                this.KPPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Data.Place[] Leave
        {
            get
            {
                return this.LeaveField;
            }
            set
            {
                this.LeaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagerCount
        {
            get
            {
                return this.ManagerCountField;
            }
            set
            {
                this.ManagerCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameFact
        {
            get
            {
                return this.NameFactField;
            }
            set
            {
                this.NameFactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameLaw
        {
            get
            {
                return this.NameLawField;
            }
            set
            {
                this.NameLawField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Notebook
        {
            get
            {
                return this.NotebookField;
            }
            set
            {
                this.NotebookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pda
        {
            get
            {
                return this.PdaField;
            }
            set
            {
                this.PdaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Data.Place PlaceId
        {
            get
            {
                return this.PlaceIdField;
            }
            set
            {
                this.PlaceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recvisits
        {
            get
            {
                return this.RecvisitsField;
            }
            set
            {
                this.RecvisitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateId
        {
            get
            {
                return this.StateIdField;
            }
            set
            {
                this.StateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VAT
        {
            get
            {
                return this.VATField;
            }
            set
            {
                this.VATField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VAT_Argument
        {
            get
            {
                return this.VAT_ArgumentField;
            }
            set
            {
                this.VAT_ArgumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkOn
        {
            get
            {
                return this.WorkOnField;
            }
            set
            {
                this.WorkOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Data.Works[] Works
        {
            get
            {
                return this.WorksField;
            }
            set
            {
                this.WorksField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Place", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    public partial class Place : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        private string RegionField;
        
        private int SuperPlacesIdField;
        
        private int TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SuperPlacesId
        {
            get
            {
                return this.SuperPlacesIdField;
            }
            set
            {
                this.SuperPlacesIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Works", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    public partial class Works : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int WorkIdField;
        
        private int WorkTypeIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkId
        {
            get
            {
                return this.WorkIdField;
            }
            set
            {
                this.WorkIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkTypeId
        {
            get
            {
                return this.WorkTypeIdField;
            }
            set
            {
                this.WorkTypeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manager", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    public partial class Manager : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CommentaryField;
        
        private string FIOField;
        
        private int IdField;
        
        private string MailField;
        
        private int SuperIdField;
        
        private string TelephoneField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commentary
        {
            get
            {
                return this.CommentaryField;
            }
            set
            {
                this.CommentaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIO
        {
            get
            {
                return this.FIOField;
            }
            set
            {
                this.FIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SuperId
        {
            get
            {
                return this.SuperIdField;
            }
            set
            {
                this.SuperIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone
        {
            get
            {
                return this.TelephoneField;
            }
            set
            {
                this.TelephoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkType", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    public partial class WorkType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    public partial class State : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Super", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    public partial class Super : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CompanyField;
        
        private string EMailField;
        
        private string HeadField;
        
        private int IdField;
        
        private string LocationField;
        
        private string PhoneField;
        
        private int PlaceIdField;
        
        private string StateField;
        
        private string TerritoryTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail
        {
            get
            {
                return this.EMailField;
            }
            set
            {
                this.EMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Head
        {
            get
            {
                return this.HeadField;
            }
            set
            {
                this.HeadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlaceId
        {
            get
            {
                return this.PlaceIdField;
            }
            set
            {
                this.PlaceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerritoryType
        {
            get
            {
                return this.TerritoryTypeField;
            }
            set
            {
                this.TerritoryTypeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRouterWCF")]
public interface IRouterWCF
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/SuperDetailsElement", ReplyAction="http://tempuri.org/IRouterWCF/SuperDetailsElementResponse")]
    Data.SuperDetails SuperDetailsElement(int superId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/SuperDetailsElement", ReplyAction="http://tempuri.org/IRouterWCF/SuperDetailsElementResponse")]
    System.Threading.Tasks.Task<Data.SuperDetails> SuperDetailsElementAsync(int superId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/ManagerList", ReplyAction="http://tempuri.org/IRouterWCF/ManagerListResponse")]
    Data.Manager[] ManagerList(int superId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/ManagerList", ReplyAction="http://tempuri.org/IRouterWCF/ManagerListResponse")]
    System.Threading.Tasks.Task<Data.Manager[]> ManagerListAsync(int superId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/PlaceList", ReplyAction="http://tempuri.org/IRouterWCF/PlaceListResponse")]
    Data.Place[] PlaceList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/PlaceList", ReplyAction="http://tempuri.org/IRouterWCF/PlaceListResponse")]
    System.Threading.Tasks.Task<Data.Place[]> PlaceListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/WorkTypeList", ReplyAction="http://tempuri.org/IRouterWCF/WorkTypeListResponse")]
    Data.WorkType[] WorkTypeList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/WorkTypeList", ReplyAction="http://tempuri.org/IRouterWCF/WorkTypeListResponse")]
    System.Threading.Tasks.Task<Data.WorkType[]> WorkTypeListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/StateList", ReplyAction="http://tempuri.org/IRouterWCF/StateListResponse")]
    Data.State[] StateList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/StateList", ReplyAction="http://tempuri.org/IRouterWCF/StateListResponse")]
    System.Threading.Tasks.Task<Data.State[]> StateListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/SuperList", ReplyAction="http://tempuri.org/IRouterWCF/SuperListResponse")]
    Data.Super[] SuperList(int place, int placeType, int workType, int state);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/SuperList", ReplyAction="http://tempuri.org/IRouterWCF/SuperListResponse")]
    System.Threading.Tasks.Task<Data.Super[]> SuperListAsync(int place, int placeType, int workType, int state);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/ManagerAdd", ReplyAction="http://tempuri.org/IRouterWCF/ManagerAddResponse")]
    void ManagerAdd(Data.Manager manager);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/ManagerAdd", ReplyAction="http://tempuri.org/IRouterWCF/ManagerAddResponse")]
    System.Threading.Tasks.Task ManagerAddAsync(Data.Manager manager);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/SuperDetailsAdd", ReplyAction="http://tempuri.org/IRouterWCF/SuperDetailsAddResponse")]
    void SuperDetailsAdd(Data.SuperDetails s);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/SuperDetailsAdd", ReplyAction="http://tempuri.org/IRouterWCF/SuperDetailsAddResponse")]
    System.Threading.Tasks.Task SuperDetailsAddAsync(Data.SuperDetails s);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/ManagerDelete", ReplyAction="http://tempuri.org/IRouterWCF/ManagerDeleteResponse")]
    void ManagerDelete(int managerId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/ManagerDelete", ReplyAction="http://tempuri.org/IRouterWCF/ManagerDeleteResponse")]
    System.Threading.Tasks.Task ManagerDeleteAsync(int managerId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/SuperDelete", ReplyAction="http://tempuri.org/IRouterWCF/SuperDeleteResponse")]
    void SuperDelete(int superId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/SuperDelete", ReplyAction="http://tempuri.org/IRouterWCF/SuperDeleteResponse")]
    System.Threading.Tasks.Task SuperDeleteAsync(int superId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/ManagerUpdate", ReplyAction="http://tempuri.org/IRouterWCF/ManagerUpdateResponse")]
    void ManagerUpdate(Data.Manager manager);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/ManagerUpdate", ReplyAction="http://tempuri.org/IRouterWCF/ManagerUpdateResponse")]
    System.Threading.Tasks.Task ManagerUpdateAsync(Data.Manager manager);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/SuperUpdate", ReplyAction="http://tempuri.org/IRouterWCF/SuperUpdateResponse")]
    void SuperUpdate(Data.SuperDetails super);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouterWCF/SuperUpdate", ReplyAction="http://tempuri.org/IRouterWCF/SuperUpdateResponse")]
    System.Threading.Tasks.Task SuperUpdateAsync(Data.SuperDetails super);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRouterWCFChannel : IRouterWCF, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RouterWCFClient : System.ServiceModel.ClientBase<IRouterWCF>, IRouterWCF
{
    
    public RouterWCFClient()
    {
    }
    
    public RouterWCFClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RouterWCFClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RouterWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RouterWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Data.SuperDetails SuperDetailsElement(int superId)
    {
        return base.Channel.SuperDetailsElement(superId);
    }
    
    public System.Threading.Tasks.Task<Data.SuperDetails> SuperDetailsElementAsync(int superId)
    {
        return base.Channel.SuperDetailsElementAsync(superId);
    }
    
    public Data.Manager[] ManagerList(int superId)
    {
        return base.Channel.ManagerList(superId);
    }
    
    public System.Threading.Tasks.Task<Data.Manager[]> ManagerListAsync(int superId)
    {
        return base.Channel.ManagerListAsync(superId);
    }
    
    public Data.Place[] PlaceList()
    {
        return base.Channel.PlaceList();
    }
    
    public System.Threading.Tasks.Task<Data.Place[]> PlaceListAsync()
    {
        return base.Channel.PlaceListAsync();
    }
    
    public Data.WorkType[] WorkTypeList()
    {
        return base.Channel.WorkTypeList();
    }
    
    public System.Threading.Tasks.Task<Data.WorkType[]> WorkTypeListAsync()
    {
        return base.Channel.WorkTypeListAsync();
    }
    
    public Data.State[] StateList()
    {
        return base.Channel.StateList();
    }
    
    public System.Threading.Tasks.Task<Data.State[]> StateListAsync()
    {
        return base.Channel.StateListAsync();
    }
    
    public Data.Super[] SuperList(int place, int placeType, int workType, int state)
    {
        return base.Channel.SuperList(place, placeType, workType, state);
    }
    
    public System.Threading.Tasks.Task<Data.Super[]> SuperListAsync(int place, int placeType, int workType, int state)
    {
        return base.Channel.SuperListAsync(place, placeType, workType, state);
    }
    
    public void ManagerAdd(Data.Manager manager)
    {
        base.Channel.ManagerAdd(manager);
    }
    
    public System.Threading.Tasks.Task ManagerAddAsync(Data.Manager manager)
    {
        return base.Channel.ManagerAddAsync(manager);
    }
    
    public void SuperDetailsAdd(Data.SuperDetails s)
    {
        base.Channel.SuperDetailsAdd(s);
    }
    
    public System.Threading.Tasks.Task SuperDetailsAddAsync(Data.SuperDetails s)
    {
        return base.Channel.SuperDetailsAddAsync(s);
    }
    
    public void ManagerDelete(int managerId)
    {
        base.Channel.ManagerDelete(managerId);
    }
    
    public System.Threading.Tasks.Task ManagerDeleteAsync(int managerId)
    {
        return base.Channel.ManagerDeleteAsync(managerId);
    }
    
    public void SuperDelete(int superId)
    {
        base.Channel.SuperDelete(superId);
    }
    
    public System.Threading.Tasks.Task SuperDeleteAsync(int superId)
    {
        return base.Channel.SuperDeleteAsync(superId);
    }
    
    public void ManagerUpdate(Data.Manager manager)
    {
        base.Channel.ManagerUpdate(manager);
    }
    
    public System.Threading.Tasks.Task ManagerUpdateAsync(Data.Manager manager)
    {
        return base.Channel.ManagerUpdateAsync(manager);
    }
    
    public void SuperUpdate(Data.SuperDetails super)
    {
        base.Channel.SuperUpdate(super);
    }
    
    public System.Threading.Tasks.Task SuperUpdateAsync(Data.SuperDetails super)
    {
        return base.Channel.SuperUpdateAsync(super);
    }
}
